name: CI Security Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep scan --config auto --json --output reports/semgrep.json
    
    - name: Install tfsec
      run: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

    - name: Run tfsec
      run: |
        tfsec terraform --format json --out=reports/tfsec.json

    - name: Run Gitleaks via Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/repo zricethezav/gitleaks:latest detect --source=/repo --report-format=json --report-path=/repo/reports/gitleaks.json
