name: CI Security Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep scan --config auto --json --output reports/semgrep.json
    
    - name: Install tfsec
      run: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

    - name: Run tfsec
      continue-on-error: true
      run: |
        tfsec terraform --format json --out=reports/tfsec.json
    - name: Set up Terraform
      run: |
        sudo rm -rf /usr/local/bin/terraform
        sudo apt-get update && sudo apt-get install -y unzip
        curl -fsSL https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/terraform

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Run Gitleaks via Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/repo zricethezav/gitleaks:latest detect --source=/repo --report-format=json --report-path=/repo/reports/gitleaks.json
