name: CI Security Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep scan --config auto --json --output reports/semgrep.json

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: |
        gitleaks detect --report-format json --report-path reports/gitleaks.json
