name: CI Security Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep scan --config auto --json --output reports/semgrep.json

    - name: Install Gitleaks
      run: |
        curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest `
        | grep "browser_download_url.*linux_amd64\.tar\.gz" `
        | cut -d '"' -f 4 `
        | xargs curl -L -o gitleaks.tar.gz
        tar -xzf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      run: |
        gitleaks detect --report-format json --report-path reports/gitleaks.json
